### ISSUE TITLE
Fix bug rating

### ISSUE THREAD

**Issue by loryleticee** [loryleticee/Meetwe#12]
Le page de presentation de la conference affiche la note lié au commentaire avec l'icône d'etoile . 

L'icône fa-stars est le sélecteur du déclencheur de la fonction de notation (qui normalement est uniquement dédié aux étoiles dans la Div "Stars".) 

Actuellement l'etoile dans le commentaire réagit à la fonction .
Il faut fixer le bug en choisissant le sélecteur .fa-stars enfant de la class .stars

**Comment by ibracoul** [comment]
d'accord
c'est bon
